cert-manager:
  crds:
    enabled: true

  replicaCount: 2

  webhook:
    replicaCount: 2

  cainjector:
    replicaCount: 2

clusterIssuer:
  name: letsencrypt-production
  enabled: true
  server: https://acme-v02.api.letsencrypt.org/directory
  email: cert-manager@example.com
  ingressClass: nginx
  privateKeySecretName: letsencrypt-production-account-key
