apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "devops-tracker-api.fullname" . }}
  namespace: {{ include "devops-tracker-api.namespace" . }}
  labels:
    {{- include "devops-tracker-api.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}

  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}

  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}

  selector:
    matchLabels:
      {{- include "devops-tracker-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "devops-tracker-api.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      serviceAccountName: {{ include "devops-tracker-api.serviceAccountName" . }}
      {{- if .Values.keyVault.enabled }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "devops-tracker-api.fullname" . }}-keyvault
      {{- end }}
      containers:
        - name: {{ .Values.containerName }}
          image: {{ include "devops-tracker-api.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: {{ .Values.portName }}
              containerPort: {{ .Values.containerPort }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          {{- $envSecrets := list }}
          {{- range .Values.keyVault.secrets }}
            {{- if .envVarName }}
              {{- $envSecrets = append $envSecrets . }}
            {{- end }}
          {{- end }}
          {{- if $envSecrets }}
          env:
            {{- range $envSecrets }}
            - name: {{ .envVarName }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "devops-tracker-api.fullname" $ }}-secrets
                  key: {{ .envVarName }}
            {{- end }}
          {{- end }}
          {{- if .Values.keyVault.enabled }}
          volumeMounts:
            - name: secrets-store
              mountPath: {{ .Values.keyVault.mountPath }}
              readOnly: true
          {{- end }}
