{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "devops-tracker-api.fullname" . }}-keyvault
  namespace: {{ include "devops-tracker-api.namespace" . }}
  labels:
    {{- include "devops-tracker-api.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.keyVault.secrets }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ default "secret" .objectType }}
          {{- if .objectAlias }}
          objectAlias: {{ .objectAlias }}
          {{- end }}
        {{- end }}
  {{- $envSecrets := list }}
  {{- range .Values.keyVault.secrets }}
    {{- if .envVarName }}
      {{- $envSecrets = append $envSecrets . }}
    {{- end }}
  {{- end }}
{{- end }}
