{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-tracker-api.serviceAccountName" . }}
  namespace: {{ include "devops-tracker-api.namespace" . }}
  labels:
    {{- include "devops-tracker-api.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ include "devops-tracker-api.azureClientId" . | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}