GRANT CONNECT ON DATABASE :"database_name" TO :"principal_name";

GRANT USAGE ON SCHEMA public TO :"principal_name";

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public
TO :"principal_name";

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
TO :"principal_name";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES
TO :"principal_name";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES
TO :"principal_name";