GRANT CONNECT ON DATABASE :"database_name" TO :"principal_name";

GRANT USAGE, CREATE ON SCHEMA public TO :"principal_name";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public
TO :"principal_name";

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public
TO :"principal_name";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES
TO :"principal_name";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES
TO :"principal_name";
