apiVersion: v1
kind: Service
metadata:
  name: devops-tracker
  namespace: devops-tracker
spec:
  type: ClusterIP
  selector:
    app: devops-tracker
  ports:
    - name: http
      port: 80
      targetPort: 3000