namespace: devops-tracker

image:
  repository: devopstrackerdevvsh6qw.azurecr.io/devops-tracker-api
  tag: latest
  pullPolicy: IfNotPresent
  
ingress:
  enabled: true
  className: nginx
  host: devops-tracker.local

podLabels:
  azure.workload.identity/use: "true"

serviceAccount:
  annotations:
    azure.workload.identity/client-id: "540fdb5f-20fa-42ab-9e1c-725f792f593c"

keyVault:
  enabled: true
  name: "kv-devops-tracker-dev-vs"
  tenantId: "75f05cdc-77de-4924-9d34-a77cde302855"
  clientId: "540fdb5f-20fa-42ab-9e1c-725f792f593c"
  secrets:
    - objectName: "applicationinsights-connection-string"
      objectType: "secret"
      objectAlias: "applicationinsights-connection-string"
