namespace: devops-tracker

image:
  repository: devopstrackerdevvsh6qw.azurecr.io/devops-tracker-api
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: api.devopstracker.com
  sourceWhitelist:
    enabled: true

podLabels:
  azure.workload.identity/use: "true"

azure:
  tenantId: ""
  clientId: ""

postgresBootstrap:
  enabled: false
  managedIdentityClientId: ""
  image:
    repository: devopstrackerdevvsh6qw.azurecr.io/devops-tracker-ops
    tag: postgres-entra-bootstrap
    pullPolicy: Always
  postgres:
    # runtime-aks output: postgres_server_fqdn
    host: "psql-devops-tracker-dev-swdct.postgres.database.azure.com"
    # runtime-aks output: postgres_database_name
    database: "devops_tracker"
    port: 5432
    # runtime-aks output: postgres_bootstrap_identity_name
    entraAdminUser: "id-devops-tracker-dev-postgres-bootstrap"
    # the aks workload identity that should bound to the role in postgres
    appPrincipalName: "id-devops-tracker-dev-aks-workload"

keyVault:
  enabled: true
  name: "kv-devops-tracker-dev-vs"
  secrets:
    - objectName: "applicationinsights-connection-string"
      objectType: "secret"
      objectAlias: "applicationinsights-connection-string"
