name: Check connectivity to endpoints

on:
  workflow_dispatch:

jobs:
  private-validation:
    runs-on: [self-hosted, vnet]
    environment: dev

    steps:
      - name: Validate private app endpoint
        env:
          APP_HEALTH_URL: "https://devops-tracker-29193.azurewebsites.net/health"
        run: curl --fail --silent --show-error "$APP_HEALTH_URL"

      - name: Validate public endpoint
        env:
          FRONT_DOOR_URL: ${{ secrets.FRONT_DOOR_URL }}
        run: curl --fail --silent --show-error "${FRONT_DOOR_URL}/health"